#!/usr/bin/env python3
"""
tsuruga_ply_to_bstid_object.py

Convert the aligned Tsuruga Castle point cloud into a filled 3-D occupancy
object and then into a normalized BST-ID XYH region.

Pipeline
--------
aligned PLY
  -> surface voxelization on a local metric grid
  -> small-gap closing (optional)
  -> interior filling
       * directional: WEST + EAST + UP enclosure rule
       * flood:       exterior flood-fill / enclosed-volume rule
  -> solid local voxels
  -> local ENU-like coordinates -> WGS84 lon/lat
  -> fine BST-ID XYH cells
  -> BST-ID normalization
  -> CSV / JSON / PLY outputs

The current Tsuruga alignment metadata is read from the JSON generated by
tsuruga_obj_anchor.py.

Recommended first run
---------------------
python tsuruga_ply_to_bstid_object.py ^
    tsuruga_aligned.ply ^
    --transform-json tsuruga_enu_anchor_transform.json ^
    --voxel-size 1.0 ^
    --fill-mode directional ^
    --close-iterations 1 ^
    --zx 25 --zy 25 --zh 15

Notes
-----
* BST-ID uses axis name "f" internally for height in the current reference
  implementation, while this script reports it as h in CSV/JSON.
* If the transform JSON contains no absolute anchor altitude, local U is used
  as height with anchor altitude 0 m unless --anchor-alt is supplied.
* Default normalization is "indexed-batch", because the transparent reference
  normalize() can be prohibitively slow on large solid objects.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
import time
from collections import Counter
from pathlib import Path

import numpy as np
import open3d as o3d
from pyproj import CRS, Transformer
from scipy import ndimage


# ---------------------------------------------------------------------------
# BST-ID imports
# ---------------------------------------------------------------------------

try:
    from bst_id.region_algebra import Cell, normalize, region_atoms
except ImportError as exc:
    raise SystemExit(
        "Could not import bst_id.region_algebra.\n"
        "Run this script from the BST-ID repository root or install the package."
    ) from exc

try:
    from bst_id.region_index import normalize_indexed_batch
    HAVE_INDEXED_BATCH = True
except ImportError:
    normalize_indexed_batch = None
    HAVE_INDEXED_BATCH = False


AXES = ("x", "y", "f", "t")
WEB_MERCATOR_LAT_MAX = 85.0511287798066

# Manuscript altitude quantization range.
H_MIN = -16383.0
H_MAX = 16384.0
H_SPAN = H_MAX - H_MIN


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def load_anchor_metadata(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))

    geo = data.get("geographic_anchor", {})
    lat = geo.get("latitude_deg")
    lon = geo.get("longitude_deg")
    alt = geo.get("absolute_altitude_m")

    if lat is None or lon is None:
        raise RuntimeError(
            "Transform JSON does not contain geographic_anchor latitude/longitude."
        )

    return {
        "lat": float(lat),
        "lon": float(lon),
        "alt": None if alt is None else float(alt),
        "raw": data,
    }


def parse_crop(crop_values):
    if crop_values is None:
        return None
    if len(crop_values) != 6:
        raise ValueError("--crop requires 6 values: xmin xmax ymin ymax zmin zmax")
    return tuple(float(v) for v in crop_values)


def crop_points(points: np.ndarray, crop):
    if crop is None:
        return points

    xmin, xmax, ymin, ymax, zmin, zmax = crop
    keep = (
        (points[:, 0] >= xmin) & (points[:, 0] <= xmax) &
        (points[:, 1] >= ymin) & (points[:, 1] <= ymax) &
        (points[:, 2] >= zmin) & (points[:, 2] <= zmax)
    )
    return points[keep]


def voxelize_surface(
    points: np.ndarray,
    voxel_size: float,
    margin_voxels: int,
):
    """
    Quantize point samples onto a dense local voxel grid.

    Returns:
        shell, origin
    where origin is the metric coordinate of voxel index (0,0,0)'s lower corner.
    """
    pmin = points.min(axis=0)
    pmax = points.max(axis=0)

    origin = np.floor(pmin / voxel_size) * voxel_size
    origin -= margin_voxels * voxel_size

    upper = np.ceil(pmax / voxel_size) * voxel_size
    upper += margin_voxels * voxel_size

    shape = np.ceil((upper - origin) / voxel_size).astype(int) + 1
    shape = tuple(int(v) for v in shape)

    ijk = np.floor((points - origin) / voxel_size).astype(np.int64)
    ijk = np.clip(ijk, [0, 0, 0], np.array(shape) - 1)

    shell = np.zeros(shape, dtype=bool)
    shell[ijk[:, 0], ijk[:, 1], ijk[:, 2]] = True

    return shell, origin


def close_shell(shell: np.ndarray, iterations: int) -> np.ndarray:
    if iterations <= 0:
        return shell

    # 26-neighbour 3x3x3 structure.  This is only used to bridge small
    # sampling gaps in the sampled surface.
    structure = np.ones((3, 3, 3), dtype=bool)
    return ndimage.binary_closing(
        shell,
        structure=structure,
        iterations=iterations,
    )


def directional_fill(shell: np.ndarray, require_ns: bool = False):
    """
    User-proposed interior rule:

      an empty voxel is filled if a shell voxel exists:
        * somewhere to the WEST on the same (y,z) scanline,
        * somewhere to the EAST on the same (y,z) scanline,
        * somewhere ABOVE on the same (x,y) vertical column.

    Optionally require north/south enclosure too.

    X = East, Y = North, Z = Up.
    """

    # WEST: any occupied voxel at smaller x.
    west = np.zeros_like(shell)
    cum = np.maximum.accumulate(shell, axis=0)
    west[1:, :, :] = cum[:-1, :, :]

    # EAST: any occupied voxel at larger x.
    east = np.zeros_like(shell)
    cum = np.maximum.accumulate(shell[::-1, :, :], axis=0)[::-1, :, :]
    east[:-1, :, :] = cum[1:, :, :]

    # UP: any occupied voxel at larger z.
    up = np.zeros_like(shell)
    cum = np.maximum.accumulate(shell[:, :, ::-1], axis=2)[:, :, ::-1]
    up[:, :, :-1] = cum[:, :, 1:]

    interior = (~shell) & west & east & up

    if require_ns:
        south = np.zeros_like(shell)
        cum = np.maximum.accumulate(shell, axis=1)
        south[:, 1:, :] = cum[:, :-1, :]

        north = np.zeros_like(shell)
        cum = np.maximum.accumulate(shell[:, ::-1, :], axis=1)[:, ::-1, :]
        north[:, :-1, :] = cum[:, 1:, :]

        interior &= south & north

    solid = shell | interior
    return solid, interior


def flood_fill(shell: np.ndarray):
    """
    Fill all empty voxels not reachable from the padded exterior.

    Equivalent conceptually to a 3-D exterior flood fill.
    """
    structure = ndimage.generate_binary_structure(rank=3, connectivity=1)
    solid = ndimage.binary_fill_holes(shell, structure=structure)
    interior = solid & (~shell)
    return solid, interior


def voxel_centers(mask: np.ndarray, origin: np.ndarray, voxel_size: float):
    ijk = np.argwhere(mask)
    centers = origin + (ijk.astype(np.float64) + 0.5) * voxel_size
    return ijk, centers


def save_centers_ply(path: Path, centers: np.ndarray):
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(centers)
    if not o3d.io.write_point_cloud(str(path), pcd, write_ascii=False):
        raise RuntimeError(f"Could not write {path}")


def make_local_to_wgs84(anchor_lat: float, anchor_lon: float):
    """
    Use a local azimuthal-equidistant CRS centered on the selected anchor.
    For the ~100-150 m castle extent this gives a convenient ENU-like
    East/North metric mapping.
    """
    local_crs = CRS.from_proj4(
        f"+proj=aeqd +lat_0={anchor_lat:.12f} "
        f"+lon_0={anchor_lon:.12f} +datum=WGS84 +units=m +no_defs"
    )
    wgs84 = CRS.from_epsg(4326)
    return Transformer.from_crs(local_crs, wgs84, always_xy=True)


def lonlat_to_webmercator_prefix(
    lon_deg: np.ndarray,
    lat_deg: np.ndarray,
    z: int,
):
    """
    Slippy/Web-Mercator hierarchical integer cell index at zoom z.
    """
    n = float(1 << z)

    lon = ((lon_deg + 180.0) % 360.0) - 180.0
    lat = np.clip(lat_deg, -WEB_MERCATOR_LAT_MAX, WEB_MERCATOR_LAT_MAX)

    x_norm = (lon + 180.0) / 360.0

    lat_rad = np.radians(lat)
    y_norm = (
        1.0
        - np.arcsinh(np.tan(lat_rad)) / math.pi
    ) / 2.0

    ix = np.floor(x_norm * n).astype(np.int64)
    iy = np.floor(y_norm * n).astype(np.int64)

    max_i = (1 << z) - 1
    ix = np.clip(ix, 0, max_i)
    iy = np.clip(iy, 0, max_i)

    return ix, iy


def altitude_to_prefix(h_m: np.ndarray, z: int):
    """
    BST-ID manuscript altitude quantization:
        [-16383, 16384] m
    """
    n = float(1 << z)
    u = (h_m - H_MIN) / H_SPAN
    # Keep endpoint exactly inside the finite index domain.
    u = np.clip(u, 0.0, np.nextafter(1.0, 0.0))
    ih = np.floor(u * n).astype(np.int64)
    return ih


def unique_bstid_triplets(
    centers_enu: np.ndarray,
    anchor_lat: float,
    anchor_lon: float,
    anchor_alt: float,
    zx: int,
    zy: int,
    zh: int,
):
    transformer = make_local_to_wgs84(anchor_lat, anchor_lon)

    east = centers_enu[:, 0]
    north = centers_enu[:, 1]
    up = centers_enu[:, 2]

    lon, lat = transformer.transform(east, north)
    lon = np.asarray(lon, dtype=np.float64)
    lat = np.asarray(lat, dtype=np.float64)

    h = anchor_alt + up

    ix, iy = lonlat_to_webmercator_prefix(lon, lat, zx)
    # Compute y independently if zx != zy.
    if zy != zx:
        _, iy = lonlat_to_webmercator_prefix(lon, lat, zy)

    ih = altitude_to_prefix(h, zh)

    triplets = np.column_stack((ix, iy, ih))
    triplets = np.unique(triplets, axis=0)

    return triplets


def triplets_to_cells(triplets: np.ndarray, zx: int, zy: int, zh: int):
    cells = []
    append = cells.append
    for ix, iy, ih in triplets:
        append(
            Cell.from_parts(
                x=(zx, int(ix)),
                y=(zy, int(iy)),
                f=(zh, int(ih)),
            )
        )
    return cells


def normalize_cells(cells, mode: str):
    if mode == "indexed-batch":
        if not HAVE_INDEXED_BATCH:
            raise RuntimeError(
                "normalize_indexed_batch() was not found in bst_id.region_index.\n"
                "Add the indexed normalization implementation or use "
                "--normalizer reference for a small test case."
            )
        return normalize_indexed_batch(cells)

    if mode == "reference":
        if len(cells) > 10_000:
            print(
                "WARNING: reference normalize() has a conservative high-order "
                "cost and may be very slow for this many cells.",
                file=sys.stderr,
            )
        return normalize(cells)

    raise ValueError(mode)


def extract_cell_row(cell):
    """
    Current reference Cell stores zooms/values in x,y,f,t order.
    Export f as h in the CSV.
    """
    zooms = tuple(cell.zooms)
    values = tuple(cell.values)

    return {
        "zx": zooms[0],
        "ix": values[0],
        "zy": zooms[1],
        "iy": values[1],
        "zh": zooms[2],
        "ih": values[2],
    }


def zoom_vector_statistics(cells):
    counter = Counter()
    axis_merged = Counter()

    for c in cells:
        row = extract_cell_row(c)
        zv = (row["zx"], row["zy"], row["zh"])
        counter[zv] += 1

    return counter


def save_prefix_csv(path: Path, cells):
    with path.open("w", newline="", encoding="utf-8") as f:
        fieldnames = ["zx", "ix", "zy", "iy", "zh", "ih"]
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for cell in cells:
            w.writerow(extract_cell_row(cell))


def verify_normalized_semantics(fine_cells, normalized_cells, zx, zy, zh):
    working_zoom = {"x": zx, "y": zy, "f": zh}
    a = region_atoms(fine_cells, working_zoom)
    b = region_atoms(normalized_cells, working_zoom)
    return a == b, len(a), len(b)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()

    ap.add_argument("ply", type=Path, help="Aligned local ENU point cloud PLY")
    ap.add_argument(
        "--transform-json",
        type=Path,
        default=Path("tsuruga_enu_anchor_transform.json"),
    )

    ap.add_argument("--voxel-size", type=float, default=1.0)
    ap.add_argument("--margin-voxels", type=int, default=2)

    ap.add_argument(
        "--fill-mode",
        choices=["directional", "flood"],
        default="directional",
        help="Interior filling rule",
    )
    ap.add_argument(
        "--close-iterations",
        type=int,
        default=1,
        help="3x3x3 binary closing iterations for small surface gaps",
    )
    ap.add_argument(
        "--require-ns",
        action="store_true",
        help="Directional mode: additionally require north and south shell enclosure",
    )

    ap.add_argument(
        "--crop",
        type=float,
        nargs=6,
        metavar=("XMIN", "XMAX", "YMIN", "YMAX", "ZMIN", "ZMAX"),
        help="Optional local metric crop before voxelization",
    )

    ap.add_argument("--zx", type=int, default=25)
    ap.add_argument("--zy", type=int, default=25)
    ap.add_argument("--zh", type=int, default=15)

    ap.add_argument(
        "--anchor-alt",
        type=float,
        default=None,
        help=(
            "Absolute altitude [m] of the geographic anchor. "
            "If omitted and JSON altitude is null, 0 m is used."
        ),
    )

    ap.add_argument(
        "--normalizer",
        choices=["indexed-batch", "reference"],
        default="indexed-batch",
    )

    ap.add_argument(
        "--verify",
        action="store_true",
        help="Expand normalized cells back to fine BST-ID zoom and verify exact equality",
    )

    ap.add_argument(
        "--out-prefix",
        default="tsuruga_object",
        help="Prefix for generated files",
    )

    args = ap.parse_args()

    t_all = time.perf_counter()

    # ------------------------------------------------------------------
    # Load point cloud + anchor
    # ------------------------------------------------------------------
    pcd = o3d.io.read_point_cloud(str(args.ply))
    if pcd.is_empty():
        raise RuntimeError(f"Could not load point cloud: {args.ply}")

    points = np.asarray(pcd.points)
    original_point_count = len(points)

    crop = parse_crop(args.crop)
    points = crop_points(points, crop)

    if len(points) == 0:
        raise RuntimeError("Crop removed all points.")

    anchor = load_anchor_metadata(args.transform_json)

    if args.anchor_alt is not None:
        anchor_alt = float(args.anchor_alt)
        altitude_source = "command line"
    elif anchor["alt"] is not None:
        anchor_alt = float(anchor["alt"])
        altitude_source = "transform JSON"
    else:
        anchor_alt = 0.0
        altitude_source = "local relative height; anchor altitude assumed 0 m"
        print(
            "NOTE: no absolute anchor altitude was supplied; "
            "BST-ID h uses local U with anchor altitude = 0 m."
        )

    print("Input")
    print("-----")
    print("PLY points            :", original_point_count)
    print("points after crop     :", len(points))
    print("anchor lat/lon        :", anchor["lat"], anchor["lon"])
    print("anchor altitude [m]   :", anchor_alt)
    print("altitude source       :", altitude_source)
    print("local voxel size [m]  :", args.voxel_size)
    print("fine BST-ID zooms     :", (args.zx, args.zy, args.zh))

    # ------------------------------------------------------------------
    # Surface voxelization
    # ------------------------------------------------------------------
    t0 = time.perf_counter()

    shell_raw, origin = voxelize_surface(
        points,
        voxel_size=args.voxel_size,
        margin_voxels=args.margin_voxels,
    )

    shell = close_shell(shell_raw, args.close_iterations)

    print()
    print("Surface voxelization")
    print("--------------------")
    print("grid shape            :", shell.shape)
    print("grid origin [m]       :", origin)
    print("raw shell voxels      :", int(shell_raw.sum()))
    print("closed shell voxels   :", int(shell.sum()))
    print("seconds               :", time.perf_counter() - t0)

    # ------------------------------------------------------------------
    # Interior fill
    # ------------------------------------------------------------------
    t0 = time.perf_counter()

    if args.fill_mode == "directional":
        solid, interior = directional_fill(
            shell,
            require_ns=args.require_ns,
        )
    else:
        solid, interior = flood_fill(shell)

    print()
    print("Object fill")
    print("-----------")
    print("mode                  :", args.fill_mode)
    print("interior voxels       :", int(interior.sum()))
    print("solid voxels          :", int(solid.sum()))
    print("seconds               :", time.perf_counter() - t0)

    # ------------------------------------------------------------------
    # Save local shell / solid center point clouds
    # ------------------------------------------------------------------
    out_prefix = Path(args.out_prefix)

    _, shell_centers = voxel_centers(shell, origin, args.voxel_size)
    solid_ijk, solid_centers = voxel_centers(
        solid,
        origin,
        args.voxel_size,
    )

    shell_ply = Path(f"{out_prefix}_shell_voxels.ply")
    solid_ply = Path(f"{out_prefix}_solid_voxels.ply")

    save_centers_ply(shell_ply, shell_centers)
    save_centers_ply(solid_ply, solid_centers)

    # ------------------------------------------------------------------
    # Convert solid local voxels to fine BST-ID XYH cells
    # ------------------------------------------------------------------
    t0 = time.perf_counter()

    triplets = unique_bstid_triplets(
        solid_centers,
        anchor_lat=anchor["lat"],
        anchor_lon=anchor["lon"],
        anchor_alt=anchor_alt,
        zx=args.zx,
        zy=args.zy,
        zh=args.zh,
    )

    fine_cells = triplets_to_cells(
        triplets,
        args.zx,
        args.zy,
        args.zh,
    )

    print()
    print("Fine BST-ID encoding")
    print("--------------------")
    print("solid local voxels    :", len(solid_centers))
    print("unique fine BST cells :", len(fine_cells))
    print("local->BST duplicates :", len(solid_centers) - len(fine_cells))
    print("seconds               :", time.perf_counter() - t0)

    # ------------------------------------------------------------------
    # Normalize
    # ------------------------------------------------------------------
    t0 = time.perf_counter()

    normalized = normalize_cells(fine_cells, args.normalizer)

    norm_seconds = time.perf_counter() - t0

    n_fine = len(fine_cells)
    n_norm = len(normalized)
    reduction = 0.0 if n_fine == 0 else 1.0 - (n_norm / n_fine)

    print()
    print("BST-ID Normalize")
    print("----------------")
    print("normalizer            :", args.normalizer)
    print("fine cells            :", n_fine)
    print("normalized prefixes   :", n_norm)
    print("prefix reduction      :", f"{100.0 * reduction:.3f}%")
    print("seconds               :", norm_seconds)

    # ------------------------------------------------------------------
    # Zoom-vector / anisotropy statistics
    # ------------------------------------------------------------------
    zoom_counts = zoom_vector_statistics(normalized)

    top_zoom_vectors = [
        {
            "zx": int(zv[0]),
            "zy": int(zv[1]),
            "zh": int(zv[2]),
            "count": int(count),
        }
        for zv, count in zoom_counts.most_common(30)
    ]

    merged_x = sum(
        1 for c in normalized if extract_cell_row(c)["zx"] < args.zx
    )
    merged_y = sum(
        1 for c in normalized if extract_cell_row(c)["zy"] < args.zy
    )
    merged_h = sum(
        1 for c in normalized if extract_cell_row(c)["zh"] < args.zh
    )
    anisotropic = sum(
        1
        for c in normalized
        if len(
            {
                args.zx - extract_cell_row(c)["zx"],
                args.zy - extract_cell_row(c)["zy"],
                args.zh - extract_cell_row(c)["zh"],
            }
        ) > 1
    )

    print()
    print("Normalized prefix structure")
    print("---------------------------")
    print("prefixes coarsened in x:", merged_x)
    print("prefixes coarsened in y:", merged_y)
    print("prefixes coarsened in h:", merged_h)
    print("anisotropic prefixes   :", anisotropic)
    print("top zoom vectors       :")
    for item in top_zoom_vectors[:10]:
        print(
            " ",
            (item["zx"], item["zy"], item["zh"]),
            "->",
            item["count"],
        )

    # ------------------------------------------------------------------
    # Optional exact verification
    # ------------------------------------------------------------------
    verification = {
        "requested": bool(args.verify),
        "passed": None,
        "fine_atom_count": None,
        "normalized_atom_count": None,
    }

    if args.verify:
        print()
        print("Verifying exact fine-grid BST-ID semantics ...")
        t0 = time.perf_counter()

        ok, na, nb = verify_normalized_semantics(
            fine_cells,
            normalized,
            args.zx,
            args.zy,
            args.zh,
        )

        verification.update(
            {
                "passed": bool(ok),
                "fine_atom_count": int(na),
                "normalized_atom_count": int(nb),
                "seconds": time.perf_counter() - t0,
            }
        )

        print("verification passed   :", ok)
        print("fine atoms            :", na)
        print("normalized atoms      :", nb)

        if not ok:
            raise RuntimeError(
                "Normalized BST-ID region did not reproduce the fine BST-ID occupancy."
            )

    # ------------------------------------------------------------------
    # Save normalized CSV + stats JSON
    # ------------------------------------------------------------------
    normalized_csv = Path(f"{out_prefix}_normalized_prefixes.csv")
    stats_json = Path(f"{out_prefix}_stats.json")

    save_prefix_csv(normalized_csv, normalized)

    stats = {
        "input": {
            "ply": str(args.ply),
            "transform_json": str(args.transform_json),
            "original_point_count": int(original_point_count),
            "point_count_after_crop": int(len(points)),
            "crop": crop,
        },
        "local_grid": {
            "voxel_size_m": args.voxel_size,
            "margin_voxels": args.margin_voxels,
            "grid_origin_m": origin.tolist(),
            "grid_shape": list(shell.shape),
            "raw_shell_voxels": int(shell_raw.sum()),
            "closed_shell_voxels": int(shell.sum()),
            "fill_mode": args.fill_mode,
            "close_iterations": args.close_iterations,
            "require_ns": bool(args.require_ns),
            "interior_voxels": int(interior.sum()),
            "solid_voxels": int(solid.sum()),
        },
        "georeference": {
            "anchor_latitude_deg": anchor["lat"],
            "anchor_longitude_deg": anchor["lon"],
            "anchor_altitude_m": anchor_alt,
            "altitude_source": altitude_source,
            "coordinate_convention": "+X East, +Y North, +Z Up",
        },
        "bstid": {
            "presence": "XYH",
            "internal_height_axis_name": "f",
            "fine_zoom": {
                "x": args.zx,
                "y": args.zy,
                "h": args.zh,
            },
            "unique_fine_cells": int(n_fine),
            "normalizer": args.normalizer,
            "normalized_prefixes": int(n_norm),
            "prefix_reduction_fraction": float(reduction),
            "prefix_reduction_percent": float(100.0 * reduction),
            "coarsened_prefix_count_by_axis": {
                "x": int(merged_x),
                "y": int(merged_y),
                "h": int(merged_h),
            },
            "anisotropic_prefix_count": int(anisotropic),
            "top_zoom_vectors": top_zoom_vectors,
            "normalization_seconds": float(norm_seconds),
        },
        "verification": verification,
        "outputs": {
            "shell_voxels_ply": str(shell_ply),
            "solid_voxels_ply": str(solid_ply),
            "normalized_prefixes_csv": str(normalized_csv),
            "stats_json": str(stats_json),
        },
        "total_seconds": float(time.perf_counter() - t_all),
    }

    stats_json.write_text(
        json.dumps(stats, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print()
    print("Saved")
    print("-----")
    print(shell_ply)
    print(solid_ply)
    print(normalized_csv)
    print(stats_json)


if __name__ == "__main__":
    main()
